"""empty message

Revision ID: 00510c65088f
Revises: f75081739d96
Create Date: 2024-10-20 03:13:46.008918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '00510c65088f'
down_revision: Union[str, None] = 'f75081739d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storycard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_urls', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('story_body', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storycard', schema=None) as batch_op:
        batch_op.drop_column('story_body')
        batch_op.drop_column('image_urls')

    # ### end Alembic commands ###
